blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [

    # post views
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    #path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('rssbf/', LatestPostsFeed(), name='post_feed'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')

    objects = models.Manager() 
    published = PublishedManager() 

    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'


# Create your models here.

blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.db.models import Count
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from django.views.generic import ListView
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
from taggit.models import Tag



def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 5) # 5 postów na kazdej stronie
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    return render(request,
                 'blog/post/list.html',
                 {'page': page,
                  'posts': posts,
                  'tag': tag})

def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                                  .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                .order_by('-same_tags','-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})




class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 5
    template_name = 'blog/post/list.html'


def post_share(request, post_id):
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} poleca artykuł {post.title} na blogu Frania"
            message = f"Hej, przeczytaj post {post.title} na stronie {post_url}\n\n Komentarz do artykułu dodany przez {cd['name']}: {cd['comments']}"
            send_mail(subject, message, 'blogfrania@gmail.com', [cd['to']])
            sent = True

    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})
            

# Create your views here.

blog/templates/blog/base.html
{% load blog_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style1.css' %}">
    <link rel="shortcut icon" type="image/png" href="{% static 'blog.ico' %}">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <nav class="navbar navbar-dark bg-dark mx-1 mt-1 md-1 rounded sticky-top ">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'blog:post_list'%}">Blog Frania</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
            <div class="offcanvas-header" style=" background-color: rgb(219, 219, 219);">
              <h5 class="offcanvas-title " id="offcanvasNavbarLabel" >Witaj na Blogu Frania</h5>
              <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body " style="background-color: rgb(38, 40, 41);">
              <div class="text-center"><a href="{% url 'blog:post_feed'%}" class="btn btn-outline-light " role="button" aria-pressed="true">Subskrubój kanał RSS</a></div>
              <p class=" h5 bg-dark p-1 rounded mt-2" style="background-color: rgba(68, 70, 68, 0.507)!important; color:rgb(220, 220, 247);">mamy już {% total_posts %} postów na blogu frania</p>
              <p class="bg-dark  p-1 rounded"  style="background-color: rgba(68, 70, 68, 0.507)!important; color:rgb(220, 220, 247);">Najnowsze posty</p>
              {% show_latest_posts 6 %}
              <p class="bg-dark  p-1 rounded" style="background-color: rgba(68, 70, 68, 0.507) !important ; color:rgb(220, 220, 247);">Posty budzące dyskusje!</p>
              {% get_most_commented_posts as most_commented_posts %}
              <ul>
                {% for post in most_commented_posts %}
                  <li>
                    <a href="{{ post.get_absolute_url }} " class=" text-muted text-decoration-none class">{{ post.title }}</a>
                  </li>
                {% endfor %}
              </ul>
            </div>
          </div>
        </div>
      </nav>
    <div>
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
  <div class="title m-3  text-light rounded-3 p-1  ms-auto me-auto"><p class="h1 m-2">{{ post.title }}</p></div>
  <div>
  <p class="m-2 text-muted dejta ms-auto me-auto ">
    Opublikowany {{ post.publish }} przez {{ post.author }}
    <a href="{% url 'blog:post_share' post.id %}">
      Udostępnij ten post
    </a>
  </p>
</div>
  <div class="m-2 restex ms-auto me-auto post rounded-3 ">
  <div class="m-3 pad6g6 lh-sm">{{ post.body|markdown }}</div>
 </div>
 <div class=" bg-dark title m-3 text-light rounded-3 p-1  ms-auto me-auto">
 <div>
 <h2>Podobne posty</h2>
 {% for post in similar_posts %}
   <p>
     <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
   </p>
 {% empty %}
   Nie ma jeszcze podobnych postów
 {% endfor %}
 {% with comments.count as total_comments %}
 <h2>
   Liczba komentarzy: {{ total_comments }}
 </h2>
{% endwith %}
{% for comment in comments %}
<div class="card text-light mt-2" style="background-color: rgb(37, 37, 37);">
  <div class="card-header text-muted">
     <p class="card-text">Komentarz napisany przez {{ comment.name }}
     {{ comment.created }}</p>
    </div>
 <div class="card-body">
   {{ comment.body }}
</div>
</div>
{% empty %}
 <p>Brak komentarzy.</p>
{% endfor %}
{% if new_comment %}
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>twój komentarz został dodany</strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
</div>
 <form method="post">
  {% csrf_token %}
  <label for="id_name">nazwa:</label><br> <input type="text" name="name" maxlength="80" required="" id="id_name"><br>
  <label for="id_email">Email:</label><br> <input type="email" name="email" maxlength="254" required="" id="id_email"><br>
  <label for="id_body">treść:</label><br> <textarea name="body" rows="10" cols="30" required="" id="id_body"></textarea><br>
  <input type="submit" value="Opublikuj" class="btn btn-outline-light mt-1">
</form>
</div>
{% else %}
 <h2>Dodaj nowy komentarz</h2>
 <form method="post">
  {% csrf_token %}
  <label for="id_name">nazwa:</label><br> <input type="text" name="name" maxlength="80" required="" id="id_name"><br>
  <label for="id_email">Email:</label><br> <input type="email" name="email" maxlength="254" required="" id="id_email"><br>
  <label for="id_body">treść:</label><br> <textarea name="body" rows="10" cols="30" id="id_body"></textarea><br>
  <input type="submit" value="Opublikuj" class="btn btn-outline-light mt-1">
</form>
</div>
{% endif %}
{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
  {% for post in latest_posts %}
    <li>
      <a href="{{ post.get_absolute_url }}" class=" text-muted text-decoration-none class">{{ post.title }}</a>
    </li>
  {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}Blog Frania{% endblock %}

{% block content %}
<div class="bok nmv fontp">
  <h3>"O NAS"</h3>
  <p>"najlepszy blog" ~~ czarson</p>
  <p>non nisi est sit amet facilisis magna etiam tempor orci eu lobortis elementum nibh tellus molestie nunc non blandit massa enim nec dui nunc mattis enim ut tellus elementum sagittis vitae et leo duis ut diam quam nulla porttitor massa id neque aliquam vestibulum morbi blandit cursus risus at ultrices</p>
</div>
<div class="posty">
  <div class="title m-3 me-3 text-light rounded-3 p-1"><p class="h1 mx-3">Blog Frania</p>
    {% if tag %}
    <p class="h1 mx-3">Posty oznaczone tagiem "{{ tag.name }}"</p>
  {% endif %}
  </div>
  {% for post in posts %}
  <div class="card mb-3 mx-3 carc ok90">
    <p class="card-title h2 m-3">
      <a class="text-decoration-none tipo" href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </p>
    <div class="m-3 fontp">
    <p class="card-text ">{{ post.body|markdown|truncatewords_html:40 }}</p>
    </div>
    <p class="ms-3">
      Tagi:
      {% for tag in post.tags.all %}
        <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>

    <div class="card-footer text-muted">
    <p>
      Opublikowany {{ post.publish | date:"d/m/Y" }} {{ post.publish | time:"H:i" }} przez {{ post.author }}
    </p>
  </div>
  </div>
  {% endfor %}
   {% include "pagination.html" with page=posts %}
  </div>
{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Udostępnij post{% endblock %}

{% block content %}
  {% if sent %}
    <p  class="alert alert-success m-2" role="alert">E-mail pomyślnie wysłano</p>
    <p class="text-light m-2">
      "{{ post.title }}" pomyślnie wysłano do {{ form.cleaned_data.to }}.
    </p>
  {% else %}
    <p class="title m-3 me-3 text-light rounded-3 p-1 h1">Udostępnij "{{ post.title }}" przez e-mail</p>
    <form method="post" class="text-white m-3 d-table" >
      <div class="mb-3">
      {% csrf_token %}
      <div>
          <label for="exampleInputEmail1" class="form-label">imię </label><br>
          <div class="w-50">{{ form.name }}</div>
      </div>
      <div>
          <label for="exampleInputEmail1" class="form-label">email </label><br>
          {{ form.email }}
      </div>
      <div>
          <labelor="exampleInputEmail1" class="form-label" f>email osoby do kórej chcesz wysłać:</labelor=><br>
          <input type="email" name="to" required="" id="id_to">
      </div>
      <div>
          <label for="exampleInputEmail1" class="form-label">komentarz do posta</label><br>
          <textarea name="comments" required="" id="id_to" rows="10" cols="30"></textarea>
      </div>
      <input type="submit" value="Wyślij e-mail" class="btn btn-outline-light mt-1">
    </div>
    </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<nav aria-label="Page navigation example " class="mx-3">
  <ul class="pagination ">
    {% if page.has_previous %}
     <li class="page-item "><a class="page-link" href="?page={{ page.previous_page_number }}"><span aria-hidden="true">&laquo;</span></a></li>
     {% else %}
     <li class="page-item disabled"><a class="page-link" href="#"><span aria-hidden="true">&laquo;</span></a></li>
     {% endif %}
 
    <li class="page-item"><p class="page-link">Strona {{ page.number }} z {{ page.paginator.num_pages }}</p></li>
    {% if page.has_next %}
     <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}"><span aria-hidden="true">&raquo;</span></a></li>
     {% else %}
     <li class="page-item disabled"><a class="page-link" href="#"><span aria-hidden="true">&raquo;</span></a></li>
    {% endif %}
  </ul>
</nav>